# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20160926_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Part',
        ),
    ]
