# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20161001_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programm',
            old_name='detail',
            new_name='part',
        ),
    ]
