# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20161001_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(default='Не активен', max_length=20),
        ),
    ]
